linter fix and test coverage check

diff --git a/.github/workflows/pull_request.yaml b/.github/workflows/pull_request.yaml
--- a/.github/workflows/pull_request.yaml
+++ b/.github/workflows/pull_request.yaml
@@ -23,7 +23,21 @@ jobs:
 
       - name: Run tests
         run: |
-          go test -v ./...
+          go test -coverprofile=coverage.out -v ./...
+
+      - name: Check test coverage
+        run: |
+          if [ ! -f coverage.out ]; then
+            echo "coverage.out file does not exist. Tests may have failed."
+            exit 1
+          fi
+          
+          total_coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
+          echo "Total Coverage: $total_coverage%"
+          if (( $(echo "$total_coverage < 65" | bc -l) )); then
+            echo "Test coverage is below 65%! Coverage is at $total_coverage%."
+            exit 1
+          fi
 
       - name: Setup goreleaser
         run: |
